services:
  webhook-relay:
    build: .
    container_name: webhook-relay
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json:ro
    restart: unless-stopped