name: Docker Image CI/CD
on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: samosadlaker/wled-relay:latest

      # Optional: Push a version tag
      - name: Tag and push version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION_TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          docker tag samosadlaker/wled-relay:latest samosadlaker/wled-relay:$VERSION_TAG
          docker push samosadlaker/wled-relay:$VERSION_TAG
